name: Build and Deploy

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'terraform/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.22.3

    - name: Build
      run: go build -o main .

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/url-shortener:${{ github.sha }} .
        docker push ${{ secrets.DOCKER_USERNAME }}/url-shortener:${{ github.sha }}

  # deploy:
  #   needs: build
  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v2

  #   - name: Configure AWS credentials
  #     uses: aws-actions/configure-aws-credentials@v1
  #     with:
  #       aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #       aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #       aws-region: us-east-1

  #   - name: Set up kubectl
  #     uses: azure/setup-kubectl@v1
  #     with:
  #       version: 'latest'
  #       config: ${{ secrets.KUBECONFIG }}

  #   - name: Create ConfigMap
  #     run: |
  #       kubectl create configmap redis-config --from-literal=redis_endpoint=${{ secrets.REDIS_ENDPOINT }} --from-literal=redis_port=${{ secrets.REDIS_PORT }}

  #   - name: Deploy to EKS
  #     run: |
  #       kubectl apply -f k8s/deployment.yml
  #       kubectl apply -f k8s/service.yml
  #       kubectl rollout status deployment/url-shortener