name: Provision Infrastructure

on:
  push:
    paths:
      - 'terraform/**'

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Terraform Init
      run: terraform init
      working-directory: terraform

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: terraform

    - name: Save kubeconfig
      id: save_kubeconfig
      run: echo "${{ steps.terraform.outputs.kubeconfig }}" > $HOME/.kube/config

    - name: Save Redis Endpoint
      id: save_redis_endpoint
      run: |
        echo "REDIS_ENDPOINT=${{ steps.terraform.outputs.redis_endpoint.value }}" >> $GITHUB_ENV
        echo "REDIS_PORT=${{ steps.terraform.outputs.redis_port.value }}" >> $GITHUB_ENV
